assume_extension: true
check_external_hash: true
enforce_https: true

url_ignore:
  - https://fonts.googleapis.com
  - https://fonts.gstatic.com
  - https://jeremiahharemza.com
  - https://www.linkedin.com
  - https://linkedin.com
  - https://twitter.com
  - https://x.com
  - https://reddit.com
