name: HTMLProofer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"

      - name: Install html-proofer dependencies
        working-directory: ci/htmlproofer
        run: bundle install

      - name: Build Jekyll site
        run: |
          bundle install
          bundle exec jekyll build

      - name: Run html-proofer
        working-directory: ci/htmlproofer
        run: bundle exec htmlproofer ../../_site
