name: HTMLProofer Check

on: [push, pull_request]

jobs:
  htmlproofer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3
          bundler-cache: true # Speeds up subsequent builds

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Run HTMLProofer
        run: bundle exec htmlproofer ./_site
